### ISSUE TITLE
pygame_sdl2.error is out of date

### ISSUE THREAD

**Issue by SuperEpicness** [renpy/pygame_sdl2#102]
When I tried installing pygame_sdl2 to my computer, this error keeps showing up:
`C:\Python27\pygame_sdl2>python setup.py install`
`pygame_sdl2.error is out of date.`
`Traceback (most recent call last):`
    `File "setup.py", line 110, in <module>`
`        cython("pygame_sdl2.error", libs=sdl_libs)`
`    File "C:\Python27\pygame_sdl2\setuplib.py", line 245, in cython`
`        c_fn])`
`    File "C:\Python27\lib\subprocess.py", line 185, in check_call`
`        retcode = call(*popenargs, **kwargs)`
`    File "C:\Python27\lib\subprocess.py", line 172, in call`
`        return Popen(*popenargs, **kwargs).wait()`
`    File "C:\Python27\lib\subprocess.py", line 394, in __init__`
`        erread, errwrite)`
`    File "C:\Python27\lib\subprocess.py", line 644, in _execute_child`
`        startupinfo)`
`WindowsError: [Error 2] The system cannot find the file specified`

pygame_sdl2_windeps is in the correct folder, cython is installed on my computer, and I've tried running it with the administrator command prompt as well, so what's going on?

**Comment by MyreMylar** [comment]
That most looks like a dll error to me, so probably windeps related. Could
you show us a screenshot of your pygame_sdl2 directory in windows
explorer/file manager, whatever they are calling it these days? A link to
Imgur or something is fine.

I guess you could also double check you can run python from the command
line (i.e. python is on your PATH environment variable).

**Comment by MrEpic382GIT** [comment]
https://drive.google.com/open?id=1PHVnGXpgd34Er7g6FNvFlgC7OLdN1qVR

**Comment by MyreMylar** [comment]
Ah, hang on. Have you installed the Visual Studio C compiler?

https://www.microsoft.com/en-us/download/details.aspx?id=44266

If this is the first python library you have built from source you will
need to grab that as well. The only other slightly odd thing I can spot is
that you are building pygame inside your python directory which, while I
don't think it will cause any problems, isn't necessary.

**Comment by MrEpic382GIT** [comment]
I already have the Visual C compiler installed.

**Comment by MyreMylar** [comment]
Well I'm out of ideas, let us know if you figure it out.

Good luck!

**Comment by Meithal** [comment]
I had the same issue,

To fix it I changed the line 59 in setuplib.py by
`cython_command = os.path.join(os.path.dirname(sys.executable), "cython.exe")`
