### ISSUE TITLE
Segmentation fault (something about fonts i guess)

### ISSUE THREAD

**Issue by coresistantcanary** [renpy/pygame_sdl2#112]
Hello, devs

I get "segmentation fault (core dumped)" while executing this script:
```python
import pygame_sdl2 ; pygame_sdl2.import_as_pygame()
import pygame
pygame.init()
font = pygame.font.Font(None, 20)
pygame.quit()  # segfault
```
No segmentation faults happen if i do either one of these:

* comment out the line with `font = ...`
* comment out `pygame.quit()`
* just use pygame instead of pygame_sdl2

I'm using Python3.7 on Linux Mint 19. `pygame_sdl2` installed via pip3.7 .
I'm attaching core dump and Valgrind output if they can be useful.
[pgsdl2sf.zip](https://github.com/renpy/pygame_sdl2/files/2332884/pgsdl2sf.zip)

**Comment by sheerluck** [comment]
I stumbled upon the same problem and accidentally tried to add ```del font``` right before ```pygame.quit()``` and it helped — no segfault anymore
