### ISSUE TITLE
Segmentation Fault creating pygame.surface

### ISSUE THREAD

**Issue by Ancalabro** [renpy/pygame_sdl2#119]
I'm trying to port a game I've made from pygame to pygame_sdl2. I'm currently stuck on a 'segmentation fault'. According to the python faulthandler, the line of code leading to the segmentation fault is:

image = pygame.Surface((24, 48)).convert()

Have also tried it without '.convert'. Doesn't change the result. Thoughts? Suggestions?

**Comment by uyjulian** [comment]
9f0cd5619d707c6b664e08475d335c2f29395b56 may have fixed this.
