### ISSUE TITLE
Problem with fix_virtualenv.py

### ISSUE THREAD

**Issue by philipk19238** [renpy/pygame_sdl2#137]
I'm trying to run the setup script with  ```python fix_virtualenv.py``` as specified by the README. However, I keep running into this error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/philipkungwork/.virtualenvs/pygame_sdl2/include'
```

After opening up the virtual environment located in ```/Users/philipkungwork/.virtualenvs/pygame_sdl2```, I noticed that the virtual environment does not contain the "include" folder. This is what my file directory looks like: 

```
- bin
  ...
- lib
  ...
pyvenv.cfg
```
Is there something wrong with the script? Or did I set up my virtual environment incorrectly? I followed the setup script exactly. 
@renpytom

**Comment by philipk19238** [comment]
Just following up @renpytom

**Comment by philipk19238** [comment]
Please confirm if this is a bug - I can create a pull request if so.

**Comment by renpytom** [comment]
I think it probably is a bug. It may be that running fix_virtualenv  is no longer required, when using venv to make your virtual environments.
