### ISSUE TITLE
Error trying to build on Windows

### ISSUE THREAD

**Issue by DaiZhongpeng3** [renpy/pygame_sdl2#143]
As soon as I run python setup.py install, python couldn't find the file named"command".
How can I put pygame_sdl2_windeps into the pygame_sdl2 checkout? And why python couldn't find the file?
My purpose is only to make Ren'py recognize the pyd file.
Thanks for the help!

**Comment by renpytom** [comment]
Building pygame_sdl2 directly isn't supported. I'd suggest using renpy/renpy-build to build it.
