### ISSUE TITLE
Can you add the pygame.mask Submodule

### ISSUE THREAD

**Issue by dominoxp** [renpy/pygame_sdl2#15]
I'm trying to convert my game written in pygame into an android Aplication using your libraries and Project. The problem is, that i need the pygame.mask, which doesn't seems to be implemented yet.
I would be very pleased if you can add it to your Project.
Thank you

**Comment by renpytom** [comment]
Will do.

**Comment by Connor124** [comment]
This is a problem I am having: pygame.mask is needed. I am using the modules PyTMX & PyScroll by bitcraft (https://github.com/bitcraft) which need the mask submodule to do some very basic functions.

As far as I can tell everything else works good.

**Comment by renpytom** [comment]
Which functions do you need? I looked at it this morning, and there is a lot of stuff there.

**Comment by Connor124** [comment]
**I apologise if this is a bad reply but my knowledge of Python isn't great. I think I need** `pygame.sprite.LayeredUpdates`. **The error pygame_sdl2 spits out is** `NotImplementedError: Could not import pygame_sdl2.sprite: No module named mask`

**If this isn't good enough here is my logcat:**


` Android bootstrap done. __name__ is __main__`
`Run user program, change dir and execute main.py`
`Opening APK '/data/app/com.connor.gtc-1/base.apk'`
` jpeg_decoder mode 0, colorType 4, w 3648, h 5472, sample 1, bsLength 0!!`
` jpeg_decoder mode 1, colorType 4, w 3648, h 5472, sample 2, bsLength 0!!`
` Traceback (most recent call last):`
`File "main.py", line 40, in <module>`
`     import pyscroll`
`File "lib/pyscroll/__init__.py", line 26, in <module>`
`     from .group import *`
`File "lib/pyscroll/group.py", line 14, in <module>`
`     class PyscrollGroup(pygame.sprite.LayeredUpdates):`
`File "/data/user/0/com.connor.gtc/files/lib/python2.7/site-packages/pygame_sdl2/__init__.py", line 32, in __getattr__`
`     raise NotImplementedError(self.reason)`
` NotImplementedError: Could not import pygame_sdl2.sprite: No module named mask`
`Python for android ended.`

If this still isn't good enough just tell me what you need.

Thanks a lot. -Connor

**Comment by Connor124** [comment]
@renpytom

I apologize if that's just a bunch of garbage.

**Comment by Connor124** [comment]
@renpytom

Any news?

**Comment by DaveMcGr** [comment]
@renpytom 

Is this still on-going? Or has development on the module stopped? Because I too am trying to use bitcraft's PyTMX module. I have tried to port the `pygame.mask.from_surface`, to no avail.

**Comment by bitcraft** [comment]
Hello~~. I'm the author of pytmx and pyscroll.  I'll investigate if I could possibly not require the mask module, or optimize it for pygame_sdl2.  

https://github.com/bitcraft/PyTMX/issues/78

**Comment by mikkelsenQ** [comment]
I am requesting to re-open this issue, as pygame.mask does not seem to be implemented.
