### ISSUE TITLE
pygame_sdl2.error.error: Failed loading smpeg2.dll: The specified module could not be found.

### ISSUE THREAD

**Issue by Gramps** [renpy/pygame_sdl2#42]
I set the following error when trying to play music:

```
File "src/pygame_sdl2/mixer_music.pyx", line 53, in pygame_sdl2.mixer_music.load (gen\pygame_sdl2.mixer_music.c:1050)
pygame_sdl2.error.error: Failed loading smpeg2.dll: The specified module could not be found.
```

This is when using the latest nightly build of pygame_sdl2 for Windows.  The Linux build using the non-nightly works fine though.  Can confirm that smpeg2.dll is in the pygame_sdl2 folder though.

EDIT:  Weird and possibly related, once I run the code and this error pops up my audio player stops working for a while.  Listening to music while testing (Audacious) and the player stops.

**Comment by renpytom** [comment]
Can you let me know which which version of Python (the number and the bitness) you are using? That's probably necessary for me to try to track this problem down.

**Comment by Gramps** [comment]
Sure, I was using Python 2.7 64-bit on Windows 10 64-bit.  I also have Python 2.7 32-bit installed for game dev purposes but have not yet tried it with that; however, it is also installed from the wheel file for that version.  Will attempt it later today and report back if there is a different response.

Thanks for looking into this!  Works phenomenally on Linux!

**Comment by Gramps** [comment]
Okay, I found that if I dump all the SDL2 DLL files into the project's base folder it will not crash.  I'm not sure why this behavior exists on Windows and not Linux but it seems to... at least for me.

The only issue now is figuring out why none of my fonts load anymore!

**Comment by LukeMS** [comment]
Tested a simple sound + music example on windows 7 x64 python 3.5 x86 and got the same error.
Also the same solution worked: if I copy smpeg2.dll to the project's directory it runs without errors.
