### ISSUE TITLE
Issues With Py2EXE

### ISSUE THREAD

**Issue by Gramps** [renpy/pygame_sdl2#45]
When a game is compiled to EXE with Py2EXE it silent closes with no errors.  Also strangely, I have to add the libwebp-4.dll to the folder with the EXE or it does (at least) error out; asking for that file.

I thought perhaps my script is wrong, but have tried multiple variations.  The game will work fine with no issues prior to compiling the EXE though.  Not sure what approach to take but it seems to be a mix of Pygame_SDL2 and Py2EXE as the game compiled fine prior to using it.

EDIT:  My guess is that Py2EXE is not pulling in all the right stuff for Pygame_SDL2 to function at all.

**Comment by renpytom** [comment]
That's probably true. You might want to consider telling py2exe to leave the console open, so you can look for output. There may also be missing libraries.

I don't think this is likely to be a pygame_sdl2 problem, it's very likely to be a packaging issue.

**Comment by Gramps** [comment]
Yeah, I have console running but am not sure what it should be including or not.  I noticed the code inside pygame_sdl2 for py2exe and wondered if maybe something wasn't importing correctly.  I'll tinker with it more regardless.

Do you guys use pygame_sdl2 for RenPy?  Py2exe?  If so, is there a script somewhere I could look at?

**Comment by renpytom** [comment]
We stopped using py2exe a while back. Right now, I just include a full python distribution, along with an exe file that starts it up.

**Comment by Gramps** [comment]
I can see why.  Thanks for the response!
