### ISSUE TITLE
Can't import pygame_sdl2

### ISSUE THREAD

**Issue by Numbermaniac** [renpy/pygame_sdl2#47]
When I try running fix_virtualenv.py, I get "/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 is not a symlink. Perhaps this script has already been run."

I went ahead and installed it anyway, and it seemed successful. But when I try to import it, I get this error:

    >>> import pygame_sdl2
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygame_sdl2-2.1.0-py2.7-macosx-10.5-fat.egg/pygame_sdl2/__init__.py", line 79, in <module>
        from pygame_sdl2.error import *
    ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygame_sdl2-2.1.0-py2.7-macosx-10.5-fat.egg/pygame_sdl2/error.so, 2): Symbol not found: _SDL_GetError
      Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygame_sdl2-2.1.0-py2.7-macosx-10.5-fat.egg/pygame_sdl2/error.so
      Expected in: dynamic lookup

OS X 10.11.4, Python 2.7.11...how do I fix it?

**Comment by renpytom** [comment]
Please make sure that the directory containing SDL2 is in your DYLD_LIBRARY_PATH. It looks like it isn't and that is preventing things from loading.
