### ISSUE TITLE
Missing headers on install

### ISSUE THREAD

**Issue by alucryd** [renpy/pygame_sdl2#53]
Hi there, since version 6.99.9 I haven't been able to package this because of a missing headers (well, most likely 3). Full build & install log here: https://paste.xinu.at/D3O/
Have you got any idea what could be the problem ? Happens with python 2 or 3 and inside or outside of a clean chroot.

**Comment by renpytom** [comment]
I don't have a good idea. Can you look in the gen3 directory to see if the file exists. Also, if you could figure out the version of cython you have installed, I'd appreciate it. 

Thank you.

**Comment by alucryd** [comment]
I can confirm the headers are not in the gen3 directory (nor in the gen directory when built with python 2), I'm building on Arch Linux using cython 0.24.

**Comment by alucryd** [comment]
Hi Tom, did you have time to look at this?

**Comment by Martoko** [comment]
I've had the same problem, pulling the latest version from github and installing gives me the headers just fine though.

**Comment by alucryd** [comment]
I can confirm that building the source bundled for 6.99.11 still doesn't work, but building the git HEAD does.
