### ISSUE TITLE
Fullscreen doesn't work.

### ISSUE THREAD

**Issue by YtvwlD** [renpy/pygame_sdl2#57]
When I run a game in full screen, nothing happens. This is no hang - there is just nothing to see.

This was working with pygame.

**Comment by renpytom** [comment]
Can you give me some details? Like what program you're running, and what platform you are on?

**Comment by YtvwlD** [comment]
I'm running https://github.com/pythonfoo/pySnake. (Set `FULLSCREEN=True` in `conf.py`.)

I've tried this in Xorg and Wayland. (Platform is Ubuntu.)

**Comment by YtvwlD** [comment]
Does this help you?
