### ISSUE TITLE
Unavailable nightly builds

### ISSUE THREAD

**Issue by Jartelos** [renpy/pygame_sdl2#66]
Noticed that http://nightly.renpy.org/pygame_sdl2/ gives an error 404, is there a mirror available anywhere, or would it possible to bring it back online?

Thanks.

**Comment by python346** [comment]
I am also having trouble installing pygame_sdl2 as the nightly build gives a 404 and installing using the instructions provided gives me an egg error.

**Comment by Connor124** [comment]
Just go to `http://nightly.renpy.org/current/` and click the top one.

**Comment by python346** [comment]
Thanks!

**Comment by KinmanCovey** [comment]
Created pull request #73 for this issue
