### ISSUE TITLE
Can i trust this source of pygame_sdl2?

### ISSUE THREAD

**Issue by rodjun** [renpy/pygame_sdl2#72]
I'm having a hard time building from source on windows 10 64bit with python 3.5, i found this online but i don't know what testpypi is about and why it's not on normal pypi.

https://testpypi.python.org/pypi/pygame_sdl2

That's the only pre-compiled version of pygame_sdl2 that i found for python 3.5 64bit on windows

**Comment by Connor124** [comment]
Have you cloned the Windows dependencies.

OR

Try downloading from the RenpyTom's server (http://nightly.renpy.org/current/), it's the top one.

PS: It helps if you tell us the errors you're getting.

**Comment by rodjun** [comment]
Yeah i've cloned the dependencies, the problem is related to the compiler version, the version used by python 3.5 is vc15 and that's the one i have, but setup.py returns 

ValueError: Unknown MS Compiler version 1900 


And that "nightly" is just a zip of the repo, it fails to install with the same error.

**Comment by Connor124** [comment]
Ok, try using pip ton install the wheels on PyPi
