### ISSUE TITLE
MIX_INIT_MODPLUG and MIX_INIT_FLUIDSYNTH undefined

### ISSUE THREAD

**Issue by Elinvention** [renpy/pygame_sdl2#89]
I can't build pygame_sdl2 and I found this related StackOverflow question https://stackoverflow.com/questions/48016953/pygame-sdl2-build-error-in-python-3-6-4.

I have SDL 2.0.7 from Debian testing.

**Comment by pdvrieze** [comment]
Just replacing them would be incorrect. These modules cannot be initialised. Removing the reference would be better.

**Comment by renpytom** [comment]
I'll take care of this shortly, as we don't need the MOD support.
